### ISSUE TITLE
MOSS官网无法打开，会自动重定向

### ISSUE THREAD

**Issue by xuegao-tzx** [txsun1997/MOSS#11]
[https://moss.fastnlp.top/](https://moss.fastnlp.top/)网站目前会自动302重定向至[https://survey.moss.fastnlp.top/s/Ntd4eG#/](https://survey.moss.fastnlp.top/s/Ntd4eG#/)，请问多会儿恢复呢？

**Comment by xuegao-tzx** [comment]
MOSS多会儿升级完成呢？

**Comment by txsun1997** [comment]
@xuegao-tzx 抱歉，我们暂时无法公开对外部署服务。后续可能通过hugging face等渠道部署demo。请关注本仓库README Update

**Comment by xuegao-tzx** [comment]
好的，谢谢
