### ISSUE TITLE
Some advices for your testing and development.

### ISSUE THREAD

**Issue by zwang98** [txsun1997/MOSS#13]
Since this project has gone shadow and restricted access, here's couple things you need to address if you really want go public:

- **Limitations**. This project is tagged: Fudan University. Once you go public, you should consider censorship and topic restriction. Therefore your LLMs should not be trained fully _unsupervised_ by Web sources or ANY Chinese sources. How to avoid those 'clever' players bypass these limits you set for MOSS, and public some sensitive topics, especially about politic & politicians. Try to avoid these 'landmines' could be quite tricky, 
- **Server selection**. ChatGPT and related products have extremely large group of users. Consider your first publish try was a total failure (on server quality). You should consider consulting your colleagues at Business/Economic departments. See if you could get an estimate user range and access a solid server to support it.

Honestly, I've been looking forward to see how MOSS could work better with Chinese language. I don't think Baidu ERNIE would be promisingly better than ChatGPT since it has gone business way before it has a product released.  

Colleges and Universities in China have greater potential than these profit-driven business parties. You should work closely with other friendly colleges in China, share you progress and catching up quicker.

So don't be frustrated, keep it up guys!

**Comment by txsun1997** [comment]
Thanks for your advice! We are working to make the next version ready for serving the public in China, in any terms (Chinese skills, MOSS capabilities, potential sensitive attacks, service, etc.).
