### ISSUE TITLE
【邀请码】-求邀请码一个

### ISSUE THREAD

**Issue by brianzhang** [txsun1997/MOSS#3]
三周时间就更新了一下README，希望有货真价实的东西拿出来体验使用，而不是套壳搭建

**Comment by gzzyyxh** [comment]
自己去提交waitlist申请

**Comment by shunyue1320** [comment]
> 

去哪申请？

**Comment by h3clikejava** [comment]
> 三周时间就更新了一下README，希望有货真价实的东西拿出来体验使用，而不是套壳搭建

好好读 Readme

**Comment by brianzhang** [comment]
> 

哈哈，Readme已经更新了，很详细。

**Comment by brianzhang** [comment]
> 自己去提交waitlist申请

已提交申请，没得回应

**Comment by shunyue1320** [comment]
https://moss.fastnlp.top/#/

**Comment by h3clikejava** [comment]
邀请码弄到了，注册界面怎么没了？？？

**Comment by xuegao-tzx** [comment]
> 邀请码弄到了，注册界面怎么没了？？？

刚刚看提示_为保证用户体验，MOSS 需要进行升级，现已停止服务_

**Comment by zhuam** [comment]
哪里可以申请

**Comment by chrislouis0106** [comment]
路过，方便后面收到链接通知

**Comment by txsun1997** [comment]
Hi @brianzhang @shunyue1320 @h3clikejava @xuegao-tzx 邀请码已发送至github主页显示的邮箱，请查收。

**Comment by lizilong1993** [comment]
感觉MOSS能力还是蛮强的，期待开源，此处比某个声称自己会开源但是完全不开源的公司的模型强多了
![image](https://user-images.githubusercontent.com/25758122/223308969-715c931a-626b-4725-aef9-4d15e9bb7626.png)

**Comment by lizilong1993** [comment]
速度非常快，几乎都是秒回答，中文支持的也还行。
希望中文这块能更加强大

**Comment by chrislouis0106** [comment]
@txsun1997 ，884665320@qq.com
可以发个邀请码，另外官网还在升级？

**Comment by h3clikejava** [comment]
> Hi @brianzhang @shunyue1320 @h3clikejava @xuegao-tzx 邀请码已发送至github主页显示的邮箱，请查收。

收到，感谢！祝好

**Comment by txsun1997** [comment]
@chrislouis0106  已发送

**Comment by xuegao-tzx** [comment]
> Hi @brianzhang @shunyue1320 @h3clikejava @xuegao-tzx 邀请码已发送至github主页显示的邮箱，请查收。

收到，感谢！

**Comment by Odyssey28** [comment]
> 感觉MOSS能力还是蛮强的，期待开源，此处比某个声称自己会开源但是完全不开源的公司的模型强多了 ![image](https://user-images.githubusercontent.com/25758122/223308969-715c931a-626b-4725-aef9-4d15e9bb7626.png)

Inside my name?

**Comment by MeoUoo** [comment]
@txsun1997  ，[1152835271@qq.com](mailto:1152835271@qq.com)
可以给我也发个邀请码和入口么，

**Comment by Lionelpang** [comment]
求个邀请码，邮箱：pangmingshi@163.com

**Comment by uloveqian2021** [comment]
已关注MOSS很久，同求邀请码，邮箱：1131208096@qq.com

**Comment by AnShengqiang** [comment]
求邀请码和入口：a18771733969@gmail.com

**Comment by brianzhang** [comment]
> Hi @brianzhang @shunyue1320 @h3clikejava @xuegao-tzx 邀请码已发送至github主页显示的邮箱，请查收。

收到，感谢！！

**Comment by brianzhang** [comment]
非常感谢MOSS团队提供的体验码，完整性比较高。
初步体验完的感受是：已具备智能的能力，但模型还不够完善，还需训练训练。其实中文互动理解还蛮不错的
![image](https://user-images.githubusercontent.com/766999/224601041-aeaefbb3-0195-4fd3-889b-e5669fe14c9b.png)

**Comment by brianzhang** [comment]
> 非常感谢MOSS团队提供的体验码，完整性比较高。 初步体验完的感受是：已具备智能的能力，但模型还不够完善，还需训练训练。其实中文互动理解还蛮不错的 ![image](https://user-images.githubusercontent.com/766999/224601041-aeaefbb3-0195-4fd3-889b-e5669fe14c9b.png)

现在是不是很容易触发敏感话题

![image](https://user-images.githubusercontent.com/766999/224601917-30db931c-bbff-4910-a259-4c350318b05c.png)

**Comment by txsun1997** [comment]
@brianzhang 敏感内容检测是第三方服务，还在协调调整中

**Comment by lalalyj** [comment]
已关注MOSS很久，求邀请码，邮箱：2336811715@qq.com

**Comment by bigtang5** [comment]
求邀请码，邮箱：656390690@qq.com

**Comment by zgzs90** [comment]
官网申请邀请码多久会给呢？

**Comment by hugh87** [comment]
期待体验，期待邀请码

**Comment by JuanZhio** [comment]
请求一个邀请码，2592045645@qq.com。感谢

**Comment by Smile1Smile** [comment]
已关注MOSS很久，求邀请码，邮箱：3447638036@qq.com

**Comment by Smile1Smile** [comment]
请求一个邀请码，yaoyao。感谢 zh0606726@outlook.com

**Comment by fanxiaoxiu** [comment]
好人一生平安：344237400@qq.com
~.~

**Comment by ShilongYin1210** [comment]
求个邀请码，感谢：244962954@qq.com

**Comment by hnuzhoulin** [comment]
已经提交申请，hnnuzhoulin@163.com

**Comment by jamesguo** [comment]
@txsun1997 
可以发个邀请码么 james.guo89@gmail.com

**Comment by FerdinandZhong** [comment]
麻烦也给我一个邀请码 ferdinandzhong@gmail.com

**Comment by 87-sm** [comment]
求个邀请码，感谢：2136246585@qq.com

**Comment by pretty-git** [comment]
求个邀请码，邮箱：2654784320@qq.com

**Comment by rayle01** [comment]
求邀请码 邮箱 ray_le@163.com

**Comment by Napoleone6** [comment]
> > Hi @brianzhang @shunyue1320 @h3clikejava @xuegao-tzx 邀请码已发送至github主页显示的邮箱，请查收。
> 
> 收到，感谢！！

**Comment by Napoleone6** [comment]
求邀请码，好心人～我的邮箱
823405024@qq.com

**Comment by verbin** [comment]
求个邀请码 dhb@qq.com

**Comment by jiangliqin** [comment]
跪求邀请码，1063112646@qq.com 。感谢~

**Comment by wudongfeng** [comment]
已经关注moss很久了，求个邀请码 wdfbit@163.com，感谢感谢～

**Comment by Hansonwong47** [comment]
已关注MOSS很久，同求邀请码，邮箱：wongzhangjz@gmail.com

**Comment by angefirebaby** [comment]
那个爹发我一个邀请码，邮箱：lovemekillme8@gmail.com

**Comment by hsh971223** [comment]
求个邀请码，感谢！邮箱：1829822964@qq.com

**Comment by zxniuniu** [comment]
已关注MOSS很久，同求邀请码，谢谢，邮箱：363077702@qq.com

**Comment by wuhy890926** [comment]
已关注MOSS很久，同求邀请码，邮箱：wuhy890926@163.com  ，非常感谢！

**Comment by nanfeng55** [comment]
> Hi @brianzhang @shunyue1320 @h3clikejava @xuegao-tzx 邀请码已发送至github主页显示的邮箱，请查收。

老哥，已关注MOSS很久，同求邀请码，邮箱：liuyingfeng45@qq.com，感谢

**Comment by zuorenbuneng** [comment]
同求邀请码，邮箱2449179430@qq.com

**Comment by ShuWu1201** [comment]
大佬，关注已久，求个邀请码   1224038352@qq.com
