### ISSUE TITLE
1

### ISSUE THREAD

**Issue by daisy-disc** [txsun1997/MOSS#4]

**Comment by BrightXiaoHan** [comment]
提issue麻烦你看了README之后再提，你这个就属于弱智问题。

**Comment by liulang201** [comment]
> 提issue麻烦你看了README之后再提，你这个就属于弱智问题。

这就是体现出素质，脑子问题，也不看看我提问的日期，我提问的时候README什么也没有

**Comment by ren-yc** [comment]
那么请您 Close 这个 Issue。

**Comment by BrightXiaoHan** [comment]
> > 提issue麻烦你看了README之后再提，你这个就属于弱智问题。
> 
> 这就是体现出素质，脑子问题，也不看看我提问的日期，我提问的时候README什么也没有

在一个项目里，问你自己的号什么时候收到邀请码，你不觉得自己脑子不好使么。

**Comment by gzzyyxh** [comment]
@liulang201 
笑死，fork的repo也pin在自己homepage上的人做这种蠢事毫不奇怪
