### ISSUE TITLE
为什么几乎所有资料文档都是英文？

### ISSUE THREAD

**Issue by 520LSY** [txsun1997/MOSS#7]

**Comment by Hashcoel** [comment]
你应该问，为啥编程语言都是英文的。

**Comment by 520LSY** [comment]
> 你应该问，为啥编程语言都是英文的。

不不不，我可不会问这么白痴的问题，主要是一个打着国产的名号连登录注册页面都是英文的东西实在是难以让人接受。当然如果这个东西是国外的产品我不会说什么，当然也有可能没打算面向国内。

**Comment by Hashcoel** [comment]
> > 你应该问，为啥编程语言都是英文的。
> 
> 不不不，我可不会问这么白痴的问题，主要是一个打着国产的名号连登录注册页面都是英文的东西实在是难以让人接受。当然如果这个东西是国外的产品我不会说什么，当然也有可能没打算面向国内。

接受不了可以不用，没人逼你。
